# Generated by Django 2.1.1 on 2018-10-26 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billapp', '0007_remove_bill_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='due_date',
            field=models.DateField(),
        ),
    ]
